import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import ClientProvider from "@/components/ClientProvider/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <Navbar></Navbar>
        </AppRouterCacheProvider>

        <main>
          <AppRouterCacheProvider>
            <ClientProvider>{children}</ClientProvider>
          </AppRouterCacheProvider>
        </main>
      </body>
    </html>
  );
}
